### ISSUE TITLE
Maintain multiple directory structure with muliple HTMLs

### ISSUE THREAD

**Issue by BestoSys** [anseki/grunt-htmlclean#4]
How to add multiple html files with different directory structure?

**Comment by anseki** [comment]
Hi @BestoSys, thank you for the comment.

You can specify multiple paths as an Array for `src` regardless of directory.
For example:

```js
grunt.initConfig({
  htmlclean: {
    deploy: {
      expand: true,
      cwd: 'develop/',
      src: ['dirA/index.html', 'dirB/index.html'],
      dest: 'public_html/'
    }
  }
});
```

The both `develop/dirA/index.html` and `develop/dirB/index.html` are processed.
Or, you can specify `'**/*.html'` for all HTML files under all directories in `develop` directory.

**Comment by anseki** [comment]
No reply came, and I close this issue.
